### ISSUE TITLE
Trying to launch hostbot and it does not respond to !addme or any other commands.

### ISSUE THREAD

**Issue by jeffpees** [mxew/firetable-hostbot#16]
When I set Firetable up, everything was working as expected, however the next time I tried to start it up - it did the following:

```PS C:\Users\jeffp> cd firetable-hostbot
PS C:\Users\jeffp\firetable-hostbot> node app.js
MB72pqEKktV5g277GgSqWfB4Ywj2
no DJS
no waiters
[]
0
(node:7016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at startSong (C:\Users\jeffp\firetable-hostbot\app.js:339:19)
    at nextSong (C:\Users\jeffp\firetable-hostbot\app.js:324:3)
    at C:\Users\jeffp\firetable-hostbot\app.js:99:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Listening now.```

**Comment by mxew** [comment]
Nice catch! Pushed a potential fix.
